spring:
  profiles:
    active: dev
  application:
    name: project_template
  main:
    allow-bean-definition-overriding: true  #允许bean定义覆盖
  data:
    redis:
      host: ${env.redis.host}     # Redis服务器地址
      port: ${env.redis.port}          # Redis服务器连接端口
      password: ${env.redis.password}    # Redis服务器连接密码（默认为空）
      database: ${env.redis.database}         # Redis数据库索引（默认为0）
      timeout: 60s        # 连接空闲超过N(s秒、ms毫秒，不加单位时使用毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
      # Lettuce连接池配置
      lettuce:
        pool:
          max-active: 10  # 允许最大连接数，默认8（负值表示没有限制），推荐值：大于cpu * 2，通常为(cpu * 2) + 2
          max-idle: 8     # 最大空闲连接数，默认8，推荐值：cpu * 2
          min-idle: 0     # 最小空闲连接数，默认0
          max-wait: 5s    # 连接用完时，新的请求等待时间(s秒、ms毫秒)，超过该时间抛出异常，默认-1（负值表示没有限制）

